CREATE TABLE Users
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(500) NOT NULL,
    FullName NVARCHAR(200) NULL,
    RoleName NVARCHAR(50) NOT NULL, 
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
);
GO